export const conectivos: string[] = [
    "no entanto,",
    "e aí",
    "daí",
    "além disso",
    "apesar das dificuldades,",
    "mas",
    "ainda que",
    "pelo contrário",
    "se não",
    "entretanto,",
    "e enfim,",
    "de fato",
    "Pois não,",
    "além disso,",
    "Pois não,",
    "ainda",
    "de qualquer forma",
    "por assim dizer."
];
